language: rust
sudo: false

before_script:
  - |
    pip install 'travis-cargo<0.2' --user
    export PATH=$HOME/.local/bin:$PATH


before_install:
  - export RUST_SRC_PATH=$(scripts/download_rust_source.sh)

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - scripts/assert_cargo_lock_unchanged

after_success:
  - travis-cargo coveralls --no-sudo --verify
