language: rust
sudo: true

before_script:
  - |
    pip install 'travis-cargo<0.2' --user
    export PATH=$HOME/.local/bin:$PATH
  - export RUST_TEST_THREADS=1

cache: cargo

before_install:
  - export RUST_SRC_PATH=$(scripts/download_rust_source.sh)

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libiberty-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - scripts/assert_cargo_lock_unchanged

after_success:
  # - travis-cargo --only stable coveralls --no-sudo --verify
  - git clone https://github.com/SimonKagstrom/kcov
  - |
    export LOCAL="~/.local"
    export PATH=$LOCAL/bin:$PATH
  - |
    mkdir kcov/build
    pushd kcov/build
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL ..
    make
    make install
    popd
  - $LOCAL/bin/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/lib-*
