environment:
  TARGET: x86_64-pc-windows-msvc
  msvc: 14

install:
  # Download and install rust compiler
  - curl -O "https://static.rust-lang.org/dist/rust-1.5.0-x86_64-pc-windows-msvc.exe"
  - rust-1.5.0-x86_64-pc-windows-msvc.exe /SILENT /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  # Download and install rust source
  - curl -O "https://static.rust-lang.org/dist/rustc-1.5.0-src.tar.gz"
  - tar -xf rustc-1.5.0-src.tar.gz
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -Vv
  - cargo -Vv
  - SET RUST_SRC_PATH=%CD%\rustc-1.5.0\src
  - if %msvc% == 14 CALL "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"


build: false

cache:
  - 'target -> Cargo.lock'
  - 'C:\Users\appveyor\.cargo -> Cargo.lock'

test_script:
  - cargo test --verbose
