environment:
  OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
  OPENSSL_LIB_DIR: C:\OpenSSL\lib
  OPENSSL_LIBS: ssleay32:libeay32

install:
  # Download and install OpenSSL
  - if not exist "%OPENSSL_LIB_DIR%" ( curl -O "http://slproweb.com/download/Win32OpenSSL-1_0_2e.exe" )
  - if not exist "%OPENSSL_LIB_DIR%" ( Win32OpenSSL-1_0_2e.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL" )
  # Download and install rust compiler
  - if not exist "C:\Program Files (x86)\Rust" ( curl -O "https://static.rust-lang.org/dist/rust-1.5.0-i686-pc-windows-gnu.exe" )
  - if not exist "C:\Program Files (x86)\Rust" ( rust-1.5.0-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust" )
  # Download and install rust source
  - if not exist "rustc-1.5.0\src" ( curl -O "https://static.rust-lang.org/dist/rustc-1.5.0-src.tar.gz" )
  - if not exist "rustc-1.5.0\src" ( tar -xf rustc-1.5.0-src.tar.gz )
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - SET RUST_SRC_PATH=%CD%\rustc-1.5.0\src

build: false

cache:
  - 'target -> Cargo.lock'
  - 'C:\Users\appveyor\.cargo -> Cargo.lock'
  - 'C:\OpenSSL'
  - 'C:\Program Files (x86)\Rust'
  - 'rustc-1.5.0'

test_script:
  - cargo test --verbose
