[package]
name = "libracerd"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
iron = "0.2"
router = "0.0.15"
bodyparser = "0.0.6"
hyper = "0.7"
persistent = "0.0.8"
logger = { git = "https://github.com/iron/logger.git" }
log = "0.3"
rand = "0.3"
env_logger = "0.3"
iron-hmac = "0.1"

[dependencies.racer]
# When making changes to racer, it's helpful to use a local path dependency.
# path = "/Users/jwilm/code/racer"

# racerd currently depends on a fork of racer until the changes are upstreamed
git = "https://github.com/jwilm/racer.git"
rev = "d14f27f3e7d22838d7d818969d476cffd1150531"

[dev-dependencies]
openssl = "0.7"

[dev-dependencies.json-request]
# Small request library built for testing this project. Local path dep is handy
# for working with the library.
# path = "/Users/jwilm/code/json-request"

git = "https://github.com/jwilm/json-request.git"
rev = "4fda576c58db206f6c41dafdc4f552ecf5aa6a44"
