[package]
name = "libracerd"
version = "0.2.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

build = "build.rs"

[dependencies]
docopt = "0.6"
router = "0.1.1"
persistent = "0.1"
log = "0.3"
rand = "0.3"
env_logger = "0.3"
racer = "1.2.6"
regex = "0.1"
serde = "0.7"
serde_json = "0.7"
rustc-serialize = "0.3"

[dependencies.logger]
version = "0.0.3"

[dependencies.bodyparser]
version = "0.3"

[dependencies.hyper]
version = "0.8"
default-features = false

[dependencies.iron]
version = "0.3"
default-features = false

[dependencies.iron-hmac]
version = "0.3.3"
features = ["hmac-rust-crypto"]

[dev-dependencies]
rust-crypto = "0.2.34"

[build-dependencies]
serde_codegen = "0.7"
syntex = "0.30"
