[package]
name = "libracerd"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
iron = "0.2"
router = "0.0.15"
bodyparser = "0.0.6"
hyper = "*"
persistent = "*"
logger = { git = "https://github.com/iron/logger.git" }
log = "*"
rand = "*"
env_logger = "*"
iron-hmac = "0.1"

[dependencies.racer] # requires beta or nightly
# When making changes to racer, it's helpful to use a local path dependency.
# path = "/Users/jwilm/code/racer"

# Until the necessary changes make it into master of racer, racerd will depend
# on jwilm's fork.
git = "https://github.com/jwilm/racer.git"
rev = "ba9dc11b7f5809944a47a791b63b0455e64c5ca2"

[dev-dependencies]
hyper = "0.7"
openssl = "0.7"

[dev-dependencies.json-request]
# Small request library built for testing this project. Local path dep is handy
# for working with the library.
# path = "/Users/jwilm/code/json-request"

# Using an off-master version of json-request until it properly supports this
# project.
git = "https://github.com/jwilm/json-request.git"
rev = "4fda576c58db206f6c41dafdc4f552ecf5aa6a44"
